# Generated by Django 5.2.5 on 2025-08-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Proyecto')),
                ('descripcion_detallada', models.TextField(verbose_name='Descripción detallada')),
                ('area_proponente', models.CharField(max_length=255, verbose_name='Área proponente')),
                ('responsable', models.CharField(max_length=255, verbose_name='Responsable del proyecto')),
                ('objetivos_generales', models.TextField(verbose_name='Objetivos generales')),
                ('objetivos_especificos', models.TextField(verbose_name='Objetivos específicos')),
                ('alcance_limitaciones', models.TextField(verbose_name='Alcance y limitaciones')),
                ('presupuesto_estimado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Presupuesto estimado')),
                ('cronograma_tentativo', models.TextField(verbose_name='Cronograma tentativo')),
                ('recursos_necesarios', models.TextField(verbose_name='Recursos necesarios')),
                ('beneficiarios_esperados', models.TextField(verbose_name='Beneficiarios esperados')),
                ('indicadores_exito', models.TextField(verbose_name='Indicadores de éxito')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
